#!/usr/bin/env bash

# ~/.dotfiles/stowall: Stow all packages
# copied from https://github.com/ChristopherA/dotfiles-stow/blob/master/stowall

#SCRIPT_DEBUG=true
#SCRIPT_DEBUG=false

clrstandout=$(tput smso) # Inverse - marks beginning end of this script
clrcommand=$(tput bold) # bold - marks calling other functions or scripts
clrunder=$(tput smul) # underline - marks comments
clrwarning=$(tput setaf 3) # yellow - marks warnings
clrerror=$(tput setaf 1) # red - marks errors
clrreset=$(tput sgr0) #normal - resets all

if $SCRIPT_DEBUG; then echo "${clrstandout}Stowing files in ${PWD}.${clrreset}"; fi

ignored_packages=()
if [ -f .stowall-ignore ]; then
  while IFS= read -r line || [ -n "$line" ]; do
    [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
    ignored_packages+=("$line")
  done < .stowall-ignore
fi

cd ~/.dotfiles
for files in ~/.dotfiles/*; do
  if [ -d ${files} ]; then
    package_name=$(basename $files)
    if [[ " ${ignored_packages[@]} " =~ " ${package_name} " ]]; then
      if $SCRIPT_DEBUG; then echo "${clrwarning}${package_name} ignored.${clrreset}"; fi
      continue
    fi
    stow -R $package_name
    if $SCRIPT_DEBUG; then echo "$package_name stowed."; fi
  fi
done
cd - > /dev/null

if $SCRIPT_DEBUG; then echo "${clrstandout}All packages stowed or re-stowed.${clrreset}"; fi
